### PR TITLE
Added Bahasa Indonesia translation

### PR DESCRIPTION
**Pull request by etherealxx**

### CODE REVIEW

**Review by DBChoco — APPROVED** [review]
Jazzaka Lahu khairan

**Review by DBChoco — CHANGES_REQUESTED** [review]
Can you copy and paste the same package.json and yarn.lock from the repository please ? I don't want them to be changed for now.
Jazzaka Lahu khairan, I'll merge as soon as you are done

**Review by DBChoco — APPROVED** [review]
Jazzaka Lahu khairan once again akhi.

**Comment by etherealxx** [comment]
Did it. Jazakallah khairan.

**Comment by DBChoco** [comment]
I'm quite busy these weeks, but once I get the chance to get some more upgrades to the software, I'll release a new version inshaAllah.
Obviously you'll receive all due credit once it's done.
Baraka Lahu feek for the help, and if you have any suggestions, don't hesitate to contact me.
Assalam alaykoum wa Rahmatou Lahi wa Baraketu.

**Pull request merged**
