### PR TITLE
feat: add Persian language

### PR DESCRIPTION
**Pull request by meypod**
I didn't translate the copyright message
Isn't this project licensed under MIT ?
or is it copyrighted ?

### CODE REVIEW

**Comment by DBChoco** [comment]
The project is not copyrighted, you can use it however you want, but still have to mention the sources.
Added to copyright at the time because I thought it was cool haha, but removed it soon after, I should remove it from source as well.

About the translation, Jazzaka Lahu khairan, I'll check it right away

**Comment by DBChoco** [comment]
Shouldn't the "..." before the quote of the Quran come before the text ? I don't know Persian but it seems like it reads from right to left no ?

**Comment by meypod** [comment]
the problem is with the web/editor
`...` is in fact before the text, It's just that the whole file is rendered left to right
I invite you to put your cursor before the `'` (first quote) and then press right arrow to see how your cursor moves. you will be surprised

**Comment by DBChoco** [comment]
https://github.com/DBChoco/Muezzin/commit/14cfa2f8f62477bbe4dbcc817f1c36d6e800c73e Fixed "..."

**Pull request merged**
