### PR TITLE
fix: uzbek language is added

### PR DESCRIPTION
**Pull request by definem**

### CODE REVIEW

**Comment by DBChoco** [comment]
Assalam Alaykoum, Jazzaka Lahu khairan !
Does this look good to you ?
image
image

It seems like there is a problem with the months, I'll try to fix that InshaAllah

**Comment by DBChoco** [comment]
For now the names of the months and days will be generated in English, it seems like I can't get it to automatically use the Uzbek names.

**Comment by definem** [comment]
Va alaykum assalam. Look, 

image

in this place, the word of `Peshin` should come before `gacha` word. Then it would be in the proper place. 


In some words, the place would be slightly different.

**Review by definem — COMMENTED** [review]
u may merge

**Comment by DBChoco** [comment]
image
I hope this this better, I changed the place and put the name of the prayers before "Peshin".
I'll merge it then, Jazzaka Lahu khairan.

**Pull request merged**
